---
title: Тестовый сайт
timezone: Europe/Kiev
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
exclude:
- README.md
- CNAME
- Makefile
