---
url: https://test.de.co.ua
baseurl: ''

title: Тестовий сайт
description: Тіпа, блоґ.
copyright: © dk487
timezone: Europe/Kiev

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  og:
    title: OpenGraphSplash
    output: true

defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: og
  values:
    layout: og_svg
    permalink: /og/:year/:month/:day/:title.svg

exclude:
- README.md
- CNAME
- Makefile
