version: 2.1

workflows:
  default-workflow:
    jobs:
      - jekyll-build

jobs:
  jekyll-build:
    docker:
      - image: kastaneda/jekyll-ci
    working_directory: /srv/jekyll
    steps:
      - checkout
      - run:
          name: "Build the site"
          command: "jekyll build"
      - run:
          name: "Run HTML-Proofer"
          command: "make test-local"
