version: 2.1

workflows:
  default-workflow:
    jobs:
      - jekyll-build

jobs:
  jekyll-build:
    docker:
      - image: jekyll/jekyll
    steps:
      - checkout
      - run:
          name: "Build the site"
          command: "cd ~/project; ls -l; whoami; jekyll build"

